### PR TITLE
Cassandra support 4.1.0-5.0.4

### PR DESCRIPTION
**Pull request by piotrmaslanka**
.

### CODE REVIEW

**Comment by piotrmaslanka** [comment]
Naturally depends on #9 .

**Comment by bhavin192** [comment]
Hello @piotrmaslanka, have you been using this in your clusters? I will try to get this merged in next few days.

**Comment by piotrmaslanka** [comment]
> Collaborator
> ###

Sure, I'm running it in production.

**Comment by piotrmaslanka** [comment]
I'm proud to admit that my solution also works for Cassandra 5.0.4:
image

**Comment by piotrmaslanka** [comment]
I considerer this repository abandoned.

**Comment by piotrmaslanka** [comment]
Therefore I started my own, that supports Cassandra 5.0.2 and sending traces to Jaeger via TCP:
[https://github.com/smok-serwis/cassandra-jaeger-tracing](https://github.com/smok-serwis/cassandra-jaeger-tracing)

**Comment by bhavin192** [comment]
Hello @piotrmaslanka, sorry I haven't been able to spend time on this project hence no activity from my side. Not out of reluctance. You have contributed a good amount of work to this project and I appreciate that. 
I'm okay if you can take the whole repo and then continue your commits on top of that, that way we follow the license/copyright correctly and commit history intact. 

Anyway, I will leave that up to you (as long as credits are given with link to this repo I guess we should be fine from the license point of view). Thank you for the work you did, and sorry I was not able to review PRs and get those merged in time.

**Comment by piotrmaslanka** [comment]
OK, you won't be forgotten, because that would be a crime. Thank you for your blessings.

**Pull request closed without merging**
